export const navBarList = [
    {
      _id: 1001,
      title: "Home",
      link: "/",
    },
    {
      _id: 1002,
      title: "Products",
      link: "/products",
    },
    {
      _id: 1003,
      title: "About",
      link: "/about",
    },
    {
      _id: 1004,
      title: "Contact",
      link: "contact",
    }
  ];

  export const paginationItems = [
    {
      _id: "p1",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Pipe Scaffolding",
      price: "35.00",
      info: "#",
      badge: true,
      badgeName: "New",
    },
    {
      _id: "p2",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Casuarina Wood",
      price: "35.00",
      info: "#",
      badge: true,
      badgeName: "Top Selling",
    },
    {
      _id: "p3",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Silver Wood",
      price: "35.00",
      info: "#",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p4",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Runner",
      price: "35.00",
      info: "3x2 Runner and 4x2 Runner",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p5",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Shuttering Plywood",
      price: "35.00",
      info: "#",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p6",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Flanks",
      price: "35.00",
      info: "6 to 12 inch",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p7",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Shed work",
      price: "35.00",
      info: "#",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p8",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Bamboo",
      price: "35.00",
      info: "#",
      badge: false,
      badgeName: "New",
    },
    {
      _id: "p9",
      img: "https://t3.ftcdn.net/jpg/04/62/93/66/360_F_462936689_BpEEcxfgMuYPfTaIAOC1tCDurmsno7Sp.jpg",
      productName: "Bamboo ladder",
      price: "35.00",
      info: "#",
      badge: false,
      badgeName: "New",
    },
    
  ]
  export const testimonal = [
    {
      id: 1,
      name: "ROGER SCOTT",
      post: "MARKETING MANAGER",
      desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
      cover: "https://static.vecteezy.com/system/resources/previews/000/593/472/original/vector-business-men-icon.jpg",
    },
    {
      id: 2,
      name: "ROGER SCOTT",
      post: "MARKETING MANAGER",
      desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
      cover: "https://static.vecteezy.com/system/resources/previews/000/593/472/original/vector-business-men-icon.jpg",
    },
    {
      id: 3,
      name: "ROGER SCOTT",
      post: "MARKETING MANAGER",
      desc: "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.",
      cover: "https://static.vecteezy.com/system/resources/previews/000/593/472/original/vector-business-men-icon.jpg",
    },
  ]
